`compare_pams.Rmd` produces an automated status report comparing two PAMS datasets
RMI-PACTA/workflow.pams.qa pull request #3
Opened 2023-08-02 13:11 UTC by jdhoffa

In this PR, I update the `compare_pams.Rmd` file to produce an automated status report, comparing two PAMS datasets. 

Expectations are checked between the two datasets. Succesful expectations yield a blue message, failed expectations yield a red warning. 

In certain cases, threshold values are required (e.g. we don't expect global production to change by more than X%). These threshold values can be updated in the `config.yml`. 

 
<img width="947" alt="Screenshot 2023-08-02 at 15 10 36" src="https://github.com/RMI-PACTA/workflow.pams.qa/assets/8741309/b8ec6b12-847d-482b-83a1-aa8429013c3a">

2023-08-02 14:56 UTC, cjyetman commented
Is this section supposed to look like this?
<img width="812" alt="Screenshot 2023-08-02 at 16 55 56" src="https://github.com/RMI-PACTA/workflow.pams.qa/assets/1708872/d0829949-b5e7-4a84-aaba-c6353633f052">

2023-08-02 15:21 UTC, jacobvjk requested changes
one condition is incomplete and we likely want all sections to be returned with `echo = FALSE`

2023-08-02 15:21 UTC, jacobvjk commented on compare_pams.Rmd
> +``` {r sectors}
As CJ already pointed out, this section should likely be `echo = FALSE` and have alternatives displayed where the if condition is not met, like all other sections?

2023-08-02 15:21 UTC, jacobvjk commented on compare_pams.Rmd
> +``` {r sectors}
seeing below that no else condition is needed... but echo remains a point

2023-08-02 15:21 UTC, jacobvjk commented on compare_pams.Rmd
> +if (length(gained_sectors) == 0 && length(lost_sectors)) {
```suggestion
if (length(gained_sectors) == 0 && length(lost_sectors) == 0) {
```

2023-08-15 09:24 UTC, jacobvjk approved these changes
lgtm

2023-08-15 13:58 UTC, merged